import React, { useState, useRef } from 'react';
import { useLanguage } from '../context/LanguageContext';
import { usePermissions } from '../context/PermissionContext';
import { X, PlusCircle, CheckCircle2, Image as ImageIcon, Phone, MapPin, Tag, DollarSign, LogIn, Sparkles, ShieldCheck, Upload, Video, Film, Trash2, Play, Wand2, Loader2, Bot, Crown, Star, Globe } from 'lucide-react';
import { CarListing } from '../types';
import { broadcastNotification } from '../lib/messaging';
import { INTERNATIONAL_COUNTRIES } from '../lib/locations';
import { saveListingToFirestore } from '../lib/listingsService';
import { uploadFileToFirebaseStorage, uploadDataUrlToFirebaseStorage } from '../lib/storageService';

interface CreateAdModalProps {
  isOpen: boolean;
  onClose: () => void;
  isLoggedIn: boolean;
  onOpenProfile: () => void;
  onAddListing?: (newListing: CarListing) => void;
}

export const CreateAdModal: React.FC<CreateAdModalProps> = ({
  isOpen,
  onClose,
  isLoggedIn,
  onOpenProfile,
  onAddListing,
}) => {
  const { language, t } = useLanguage();
  const { requestPermission } = usePermissions();

  const [title, setTitle] = useState('');
  const [category, setCategory] = useState<'mobile' | 'tools' | 'appliances' | 'electronics' | 'car' | 'realestate' | 'service'>('mobile');
  const [condition, setCondition] = useState<'new' | 'used' | 'certified'>('used');
  const [type, setType] = useState<'sale' | 'rent'>('sale');
  const [priceUSD, setPriceUSD] = useState<string>('150');
  const [priceSYP, setPriceSYP] = useState<string>('2250000');
  const [city, setCity] = useState('سوريا - دمشق');
  const [phone, setPhone] = useState('0944112233');
  const [description, setDescription] = useState('');

  // Media state (Unlimited Photos + Unlimited Videos)
  const [imagesList, setImagesList] = useState<string[]>([]);
  const [videosList, setVideosList] = useState<string[]>([]);
  const [activeMediaTab, setActiveMediaTab] = useState<'photos' | 'video'>('photos');
  const [pastedUrl, setPastedUrl] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // AI Assistant state
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGeneratingText, setIsGeneratingText] = useState(false);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const [aiStatusMessage, setAiStatusMessage] = useState<string | null>(null);

  // Featured Ad Subscription plan
  const [featuredPlan, setFeaturedPlan] = useState<'standard' | 'golden' | 'vip'>('standard');

  const [isUploadingMedia, setIsUploadingMedia] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  if (!isOpen) return null;

  const handleAIGenerateAd = async () => {
    if (!aiPrompt.trim() && !title.trim()) {
      setAiStatusMessage(language === 'ar' ? 'يرجى كتابة اسم المنتَج أو فكرة الإعلان أولاً' : 'Please type an item name or quick prompt');
      return;
    }
    setIsGeneratingText(true);
    setAiStatusMessage(null);
    try {
      const res = await fetch('/api/ai/generate-ad', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          category,
          city,
          userPrompt: aiPrompt.trim() || title.trim(),
        }),
      });
      const data = await res.json();
      if (data.success) {
        if (data.title) setTitle(data.title);
        if (data.description) setDescription(data.description);
        if (data.suggestedPriceUSD) {
          setPriceUSD(String(data.suggestedPriceUSD));
          setPriceSYP(String(data.suggestedPriceSYP || data.suggestedPriceUSD * 15000));
        }
        setAiStatusMessage(language === 'ar' ? '✨ تم صياغة وتجهيز تفاصيل الإعلان بنجاح بواسطة الذكاء الاصطناعي!' : '✨ Ad details successfully generated by AI!');
      } else {
        setAiStatusMessage(data.error || 'حدث خطأ في خدمة التوليد');
      }
    } catch (err) {
      setAiStatusMessage(language === 'ar' ? 'فشل الاتصال بالذكاء الاصطناعي' : 'AI connection failed');
    } finally {
      setIsGeneratingText(false);
    }
  };

  const handleAIGenerateImage = async () => {
    setIsGeneratingImage(true);
    setAiStatusMessage(null);
    try {
      const res = await fetch('/api/ai/generate-ad-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title || aiPrompt || 'إعلان تجاري',
          category,
          prompt: aiPrompt,
        }),
      });
      const data = await res.json();
      if (data.success && data.imageUrl) {
        // Upload AI generated base64 image to Firebase Storage
        const cloudUrl = await uploadDataUrlToFirebaseStorage(data.imageUrl, 'ai_generated_images');
        setImagesList((prev) => [cloudUrl, ...prev]);
        setAiStatusMessage(language === 'ar' ? '🎨 تم رفع صورة الإعلان بالذكاء الاصطناعي إلى Firebase Storage!' : '🎨 AI Ad Image stored in cloud storage!');
      } else {
        setAiStatusMessage(data.error || 'فشل في تصميم صورة الإعلان');
      }
    } catch (err) {
      setAiStatusMessage(language === 'ar' ? 'فشل الاتصال بخدمة تصميم الصور' : 'AI image service error');
    } finally {
      setIsGeneratingImage(false);
    }
  };

  const handleFileUpload = async (files: FileList | File[]) => {
    if (!files || files.length === 0) return;

    setIsUploadingMedia(true);
    const count = files.length;
    setAiStatusMessage(
      language === 'ar'
        ? `⚡ جاري معالجة ورفع ${count} ${count > 1 ? 'ملفات' : 'ملف'}...`
        : `⚡ Processing & uploading ${count} media file(s)...`
    );

    try {
      const fileArray = Array.from(files);
      const uploadedImages: string[] = [];
      const uploadedVideos: string[] = [];

      for (let i = 0; i < fileArray.length; i++) {
        const file = fileArray[i];
        setAiStatusMessage(
          language === 'ar'
            ? `⚡ جاري معالجة الملف (${i + 1} من ${fileArray.length})...`
            : `⚡ Processing file (${i + 1} of ${fileArray.length})...`
        );
        const folder = file.type.startsWith('video/') ? 'listing_videos' : 'listing_images';
        const cloudUrl = await uploadFileToFirebaseStorage(file, folder);
        if (file.type.startsWith('video/')) {
          uploadedVideos.push(cloudUrl);
        } else {
          uploadedImages.push(cloudUrl);
        }
      }

      if (uploadedImages.length > 0) {
        setImagesList((prev) => [...prev, ...uploadedImages]);
      }
      if (uploadedVideos.length > 0) {
        setVideosList((prev) => [...prev, ...uploadedVideos]);
      }

      setAiStatusMessage(
        language === 'ar'
          ? `✅ تم رفع وتجهيز ${uploadedImages.length + uploadedVideos.length} ملف بنجاح!`
          : `✅ Successfully uploaded ${uploadedImages.length + uploadedVideos.length} media file(s)!`
      );
    } catch (err) {
      console.error('Error uploading media files:', err);
      setAiStatusMessage(
        language === 'ar' ? '⚠️ حدث خطأ أثناء معالجة بعض الملفات' : '⚠️ Error uploading some media files'
      );
    } finally {
      setIsUploadingMedia(false);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      handleFileUpload(e.target.files);
    }
    // Clear input value so selecting the same file again triggers change
    e.target.value = '';
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      handleFileUpload(e.dataTransfer.files);
    }
  };

  const removeImage = (index: number) => {
    setImagesList((prev) => prev.filter((_, i) => i !== index));
  };

  const removeVideo = (index: number) => {
    setVideosList((prev) => prev.filter((_, i) => i !== index));
  };

  const handleAddPastedUrl = () => {
    if (!pastedUrl.trim()) return;
    if (activeMediaTab === 'video') {
      setVideosList((prev) => [...prev, pastedUrl.trim()]);
    } else {
      setImagesList((prev) => [...prev, pastedUrl.trim()]);
    }
    setPastedUrl('');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    const fallbackImage = 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80';
    const mainImg = imagesList.length > 0 ? imagesList[0] : fallbackImage;
    const mainVid = videosList.length > 0 ? videosList[0] : undefined;

    const newAd: CarListing = {
      id: `ad-${Date.now()}`,
      title,
      category: category as any,
      condition,
      priceUSD: Number(priceUSD) || 100,
      priceSYP: Number(priceSYP) || 1500000,
      type,
      city,
      image: mainImg,
      images: imagesList.length > 0 ? imagesList : [mainImg],
      video: mainVid,
      mediaType: mainVid ? 'video' : 'image',
      phone: phone || '0944000000',
      featured: featuredPlan !== 'standard',
      featuredPlan: featuredPlan,
    };

    if (onAddListing) {
      onAddListing(newAd);
    }

    // Persist ad to Firebase Firestore and log activity
    saveListingToFirestore(newAd).catch((err) => console.error('Failed to save to Firestore:', err));

    // Trigger FCM real-time notification alert
    broadcastNotification({
      title: language === 'ar' ? `إعلان جديد: ${newAd.title}` : `New Listing: ${newAd.title}`,
      body: language === 'ar' ? `تم نشر الإعلان في قسم ${newAd.category} بسعر $${newAd.priceUSD}` : `Ad published in ${newAd.category} for $${newAd.priceUSD}`,
      category: newAd.category,
      type: 'category_listing',
    });

    setSubmitted(true);
    setTimeout(() => {
      setSubmitted(false);
      setTitle('');
      setDescription('');
      setImagesList([]);
      setVideosList([]);
      setFeaturedPlan('standard');
      onClose();
    }, 2000);
  };

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/80 backdrop-blur-md animate-fadeIn"
      onClick={onClose}
    >
      <div 
        className="bg-slate-900 border border-slate-800 rounded-3xl max-w-lg w-full p-5 sm:p-6 shadow-2xl relative overflow-hidden space-y-5 max-h-[90vh] overflow-y-auto scrollbar-none my-auto"
        onClick={(e) => e.stopPropagation()}
      >
        
        {/* Top Glowing Bar */}
        <div className="absolute top-0 right-0 left-0 h-1.5 bg-gradient-to-r from-amber-500 via-emerald-500 to-indigo-500"></div>

        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3.5">
          <div className="flex items-center space-x-2.5 space-x-reverse">
            <div className="p-2.5 bg-amber-500/20 border border-amber-500/30 text-amber-400 rounded-2xl">
              <PlusCircle className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                <span>{language === 'ar' ? 'إضافة إعلان جديد' : 'Create New Listing'}</span>
                <span className="text-[10px] bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 px-2 py-0.5 rounded-full font-bold">
                  OMS VIP
                </span>
              </h3>
              <p className="text-xs text-slate-400">
                {language === 'ar' ? 'نشر أدوات، منتجات، عقارات أو سيارات للبيع والإيجار' : 'Post tools, products, real estate or cars for sale'}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white rounded-xl transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Auth Guard Check */}
        {!isLoggedIn ? (
          <div className="bg-slate-950 border border-slate-800 rounded-2xl p-6 text-center space-y-4">
            <div className="w-16 h-16 bg-amber-500/10 border border-amber-500/30 text-amber-400 rounded-full flex items-center justify-center mx-auto">
              <ShieldCheck className="w-8 h-8" />
            </div>
            <div className="space-y-1">
              <h4 className="text-base font-bold text-white">
                {language === 'ar' ? 'يتطلب تسجيل الدخول لإضافة إعلان' : 'Login Required to Post Ad'}
              </h4>
              <p className="text-xs text-slate-400 max-w-sm mx-auto">
                {language === 'ar'
                  ? 'يرجى تسجيل الدخول بحساب OMS VIP الخاص بك لتتمكن من إضافة إعلاناتك وتلقي الاتصالات من المشترين.'
                  : 'Please log in with your OMS VIP account to post listings and receive calls from buyers.'}
              </p>
            </div>
            <button
              onClick={() => {
                onClose();
                onOpenProfile();
              }}
              className="w-full py-3 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-slate-950 font-black rounded-xl text-sm flex items-center justify-center gap-2 transition-all shadow-lg shadow-amber-500/20"
            >
              <LogIn className="w-4 h-4" />
              <span>{language === 'ar' ? 'تسجيل الدخول كـ OMS VIP الآن' : 'Log In as OMS VIP Now'}</span>
            </button>
          </div>
        ) : submitted ? (
          <div className="bg-emerald-950/60 border border-emerald-500/40 rounded-2xl p-8 text-center space-y-3">
            <CheckCircle2 className="w-14 h-14 text-emerald-400 mx-auto animate-bounce" />
            <h4 className="text-lg font-black text-white">
              {language === 'ar' ? 'تم نشر إعلانك بنجاح! 🎉' : 'Ad Published Successfully! 🎉'}
            </h4>
            <p className="text-xs text-emerald-200">
              {language === 'ar' ? 'يظهر إعلانك الآن للجميع في الصفحة الرئيسية وسوق الأدوات.' : 'Your ad is now visible to all users on the home page.'}
            </p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4 text-xs">
            {/* AI Assistant Banner & Tools */}
            <div className="bg-gradient-to-r from-purple-950/80 via-indigo-950/80 to-slate-900 border border-purple-500/40 rounded-2xl p-3.5 space-y-3 shadow-lg shadow-purple-950/30">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-xl bg-purple-500/20 border border-purple-400/40 flex items-center justify-center text-purple-300 shrink-0">
                    <Sparkles className="w-4 h-4 text-purple-300 animate-pulse" />
                  </div>
                  <div>
                    <h4 className="font-bold text-purple-200 text-xs sm:text-sm flex items-center gap-1.5">
                      <span>{language === 'ar' ? 'مساعد الذكاء الاصطناعي OMS AI 🤖✨' : 'OMS AI Ad Assistant 🤖✨'}</span>
                    </h4>
                    <p className="text-[10px] text-purple-300/80">
                      {language === 'ar' ? 'اكتب فكرة سريعة أو اسم المنتج لصياغة الإعلان وتصميم صورة بالذكاء الاصطناعي' : 'Type a quick idea to auto-generate ad text & design custom image'}
                    </p>
                  </div>
                </div>
              </div>

              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder={language === 'ar' ? 'مثال: سيارة مرسيدس 2021 نظيفة جداً بسعر ممتاز في دمشق...' : 'e.g. Clean 2021 Mercedes car in Damascus...'}
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                  className="flex-1 bg-slate-950/90 border border-purple-500/30 rounded-xl px-3 py-2 text-slate-100 placeholder-purple-300/40 text-xs focus:outline-none focus:border-purple-400"
                />
              </div>

              <div className="grid grid-cols-2 gap-2 pt-0.5">
                <button
                  type="button"
                  onClick={handleAIGenerateAd}
                  disabled={isGeneratingText}
                  className="py-2 px-3 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 disabled:opacity-60 text-white font-bold rounded-xl text-[11px] flex items-center justify-center gap-1.5 transition-all shadow-md"
                >
                  {isGeneratingText ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      <span>{language === 'ar' ? 'جاري الصياغة...' : 'Generating text...'}</span>
                    </>
                  ) : (
                    <>
                      <Bot className="w-3.5 h-3.5 text-purple-200" />
                      <span>{language === 'ar' ? 'صياغة الإعلان بالذكاء الاصطناعي ✨' : 'AI Generate Content ✨'}</span>
                    </>
                  )}
                </button>

                <button
                  type="button"
                  onClick={handleAIGenerateImage}
                  disabled={isGeneratingImage}
                  className="py-2 px-3 bg-gradient-to-r from-indigo-600 to-cyan-600 hover:from-indigo-500 hover:to-cyan-500 disabled:opacity-60 text-white font-bold rounded-xl text-[11px] flex items-center justify-center gap-1.5 transition-all shadow-md"
                >
                  {isGeneratingImage ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      <span>{language === 'ar' ? 'جاري التصميم...' : 'Designing image...'}</span>
                    </>
                  ) : (
                    <>
                      <Wand2 className="w-3.5 h-3.5 text-cyan-200" />
                      <span>{language === 'ar' ? 'تصميم صورة بالذكاء الاصطناعي 🎨' : 'AI Design Image 🎨'}</span>
                    </>
                  )}
                </button>
              </div>

              {aiStatusMessage && (
                <div className="bg-slate-950/80 border border-purple-500/40 rounded-xl p-2 text-[11px] text-purple-200 font-bold flex items-center gap-1.5 animate-fadeIn">
                  <Sparkles className="w-3.5 h-3.5 text-amber-400 shrink-0" />
                  <span>{aiStatusMessage}</span>
                </div>
              )}
            </div>

            {/* Ad Title */}
            <div className="space-y-1.5">
              <label className="block font-bold text-slate-200">
                {language === 'ar' ? 'عنوان الإعلان أو اسم المنتج *' : 'Ad Title / Product Name *'}
              </label>
              <input
                type="text"
                required
                placeholder={language === 'ar' ? 'مثال: طقم أدوات صيانة أو دريلة Bosch مستعملة' : 'e.g. Bosch Electric Drill Set'}
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-slate-200 focus:outline-none focus:border-amber-500/50"
              />
            </div>

            {/* Category & Condition */}
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <label className="block font-bold text-slate-200">
                  {language === 'ar' ? 'القسم الرئيسي' : 'Category'}
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value as any)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2.5 text-slate-200 focus:outline-none focus:border-amber-500/50"
                >
                  <option value="mobile">{language === 'ar' ? '📱 هواتف وموبايلات وأجهزة ذكية' : '📱 Phones & Mobile Devices'}</option>
                  <option value="electronics">{language === 'ar' ? '💻 إلكترونيات ولابتوبات' : '💻 Electronics & Computers'}</option>
                  <option value="car">{language === 'ar' ? '🚗 سيارات ووسائط نقل' : '🚗 Cars & Vehicles'}</option>
                  <option value="tools">{language === 'ar' ? '🔧 أدوات ومعدات صيانة' : '🔧 Tools & Equipment'}</option>
                  <option value="appliances">{language === 'ar' ? '⚡️ أجهزة منزلية ومولدات' : '⚡️ Appliances & Generators'}</option>
                  <option value="realestate">{language === 'ar' ? '🏠 عقارات وشقق' : '🏠 Real Estate'}</option>
                  <option value="service">{language === 'ar' ? '🤝 خدمات وتوصيل' : '🤝 Services & Delivery'}</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="block font-bold text-slate-200">
                  {language === 'ar' ? 'حالة المنتج' : 'Item Condition'}
                </label>
                <div className="grid grid-cols-3 gap-1 bg-slate-950 p-1 border border-slate-800 rounded-xl">
                  <button
                    type="button"
                    onClick={() => setCondition('used')}
                    className={`py-1.5 rounded-lg font-bold text-[10px] sm:text-[11px] transition-all ${
                      condition === 'used' ? 'bg-amber-600 text-white shadow' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    {language === 'ar' ? 'مستعمل ♻️' : 'Used'}
                  </button>
                  <button
                    type="button"
                    onClick={() => setCondition('certified')}
                    className={`py-1.5 rounded-lg font-bold text-[10px] sm:text-[11px] transition-all ${
                      condition === 'certified' ? 'bg-cyan-600 text-white shadow ring-1 ring-cyan-400/50' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    {language === 'ar' ? 'مفحوصة 🛡️' : 'Certified'}
                  </button>
                  <button
                    type="button"
                    onClick={() => setCondition('new')}
                    className={`py-1.5 rounded-lg font-bold text-[10px] sm:text-[11px] transition-all ${
                      condition === 'new' ? 'bg-emerald-600 text-white shadow' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    {language === 'ar' ? 'جديد ✨' : 'New'}
                  </button>
                </div>
              </div>
            </div>

            {/* Type & City */}
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <label className="block font-bold text-slate-200">
                  {language === 'ar' ? 'نوع العرض' : 'Offer Type'}
                </label>
                <select
                  value={type}
                  onChange={(e) => setType(e.target.value as any)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2.5 text-slate-200 focus:outline-none focus:border-amber-500/50"
                >
                  <option value="sale">{language === 'ar' ? 'للبيع' : 'For Sale'}</option>
                  <option value="rent">{language === 'ar' ? 'للإيجار' : 'For Rent'}</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="block font-bold text-slate-200 flex items-center justify-between">
                  <span>{language === 'ar' ? 'الدولة والمدينة (شحن وإعلانات دولية 🌍)' : 'Country & City (International Ads 🌍)'}</span>
                </label>
                <select
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2.5 text-slate-200 focus:outline-none focus:border-amber-500/50 text-sm font-medium"
                >
                  {INTERNATIONAL_COUNTRIES.map((c) => (
                    <optgroup key={c.code} label={`${c.flag} ${language === 'ar' ? c.nameAr : c.nameEn}`}>
                      {c.cities.map((ci) => {
                        const val = `${c.nameAr} - ${ci.nameAr}`;
                        return (
                          <option key={ci.nameAr} value={val}>
                            {c.flag} {c.nameAr} - {ci.nameAr}
                          </option>
                        );
                      })}
                    </optgroup>
                  ))}
                </select>
              </div>
            </div>

            {/* Price USD & SYP */}
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <label className="block font-bold text-slate-200">
                  {language === 'ar' ? 'السعر بالدولار ($)' : 'Price USD ($)'}
                </label>
                <input
                  type="number"
                  required
                  value={priceUSD}
                  onChange={(e) => {
                    setPriceUSD(e.target.value);
                    setPriceSYP(String((Number(e.target.value) || 0) * 15000));
                  }}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-emerald-400 font-mono font-bold focus:outline-none focus:border-amber-500/50"
                />
              </div>

              <div className="space-y-1.5">
                <label className="block font-bold text-slate-200">
                  {language === 'ar' ? 'السعر بالليرة السورية' : 'Price SYP'}
                </label>
                <input
                  type="number"
                  required
                  value={priceSYP}
                  onChange={(e) => setPriceSYP(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-amber-400 font-mono font-bold focus:outline-none focus:border-amber-500/50"
                />
              </div>
            </div>

            {/* Phone Contact */}
            <div className="space-y-1.5">
              <label className="block font-bold text-slate-200">
                {language === 'ar' ? 'رقم الهاتف للتواصل *' : 'Contact Phone *'}
              </label>
              <input
                type="text"
                required
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-slate-200 font-mono focus:outline-none focus:border-amber-500/50"
              />
            </div>

            {/* Media Upload Section: Unlimited Photos & Videos */}
            <div className="space-y-3 bg-slate-950/80 border border-slate-800 p-4 rounded-2xl">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <label className="font-bold text-slate-200 flex items-center gap-2 text-xs sm:text-sm">
                  <Upload className="w-4 h-4 text-amber-400" />
                  <span>{language === 'ar' ? 'منطقة نشر الصور والفيديوهات للمالك (إمكانية غير محدودة) 📸 🎥' : 'Ad Media Publishing Zone (Unlimited) 📸 🎥'}</span>
                </label>
                
                <div className="flex items-center gap-1 bg-slate-900 p-1 border border-slate-800 rounded-lg text-xs">
                  <button
                    type="button"
                    onClick={() => setActiveMediaTab('photos')}
                    className={`px-2.5 py-1 rounded-md font-bold text-[10px] flex items-center gap-1 transition-all ${
                      activeMediaTab === 'photos' ? 'bg-amber-500 text-slate-950 shadow' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    <ImageIcon className="w-3 h-3" />
                    <span>{language === 'ar' ? `صور (${imagesList.length})` : `Photos (${imagesList.length})`}</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setActiveMediaTab('video')}
                    className={`px-2.5 py-1 rounded-md font-bold text-[10px] flex items-center gap-1 transition-all ${
                      activeMediaTab === 'video' ? 'bg-indigo-600 text-white shadow' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    <Video className="w-3 h-3" />
                    <span>{language === 'ar' ? `فيديو (${videosList.length})` : `Video (${videosList.length})`}</span>
                  </button>
                </div>
              </div>

              {/* Unlimited Rule Banner */}
              <div className="bg-gradient-to-r from-emerald-950/60 via-slate-900 to-emerald-950/60 border border-emerald-500/30 rounded-xl p-2.5 flex flex-wrap items-center justify-between gap-2 text-[11px] text-emerald-300">
                <span className="flex items-center gap-1.5 font-bold">
                  <Film className="w-4 h-4 text-emerald-400 shrink-0" />
                  <span>
                    {language === 'ar'
                      ? 'إمكانية نشر الفيديوهات والصور في منطقة النشر بسهولة وبلا حدود ♾️'
                      : 'Publish unlimited photos and videos easily in the publishing area ♾️'}
                  </span>
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                  {language === 'ar' ? 'رفع غير محدود ♾️' : 'Unlimited Uploads'}
                </span>
              </div>

              {/* Upload Drop Zone */}
              <div
                onDragOver={(e) => {
                  e.preventDefault();
                  setIsDragging(true);
                }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={handleDrop}
                onClick={() => requestPermission('studio', () => fileInputRef.current?.click())}
                className={`border-2 border-dashed rounded-2xl p-4 text-center cursor-pointer transition-all ${
                  isDragging
                    ? 'border-amber-400 bg-amber-500/10 scale-[0.99]'
                    : 'border-slate-800 bg-slate-900/60 hover:border-slate-700 hover:bg-slate-900'
                }`}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  accept="image/*,video/*"
                  onChange={handleFileChange}
                  className="hidden"
                />

                <div className="space-y-2 py-2">
                  <div className="w-12 h-12 bg-amber-500/10 border border-amber-500/30 text-amber-400 rounded-2xl flex items-center justify-center mx-auto">
                    {isUploadingMedia ? (
                      <Loader2 className="w-6 h-6 text-amber-400 animate-spin" />
                    ) : activeMediaTab === 'video' ? (
                      <Film className="w-6 h-6 text-indigo-400" />
                    ) : (
                      <Upload className="w-6 h-6 text-amber-400" />
                    )}
                  </div>
                  <div>
                    <p className="text-xs font-bold text-slate-200">
                      {isUploadingMedia
                        ? (aiStatusMessage || (language === 'ar' ? 'جاري معالجة ورفع الملفات...' : 'Processing & uploading media...'))
                        : language === 'ar'
                        ? activeMediaTab === 'video'
                          ? 'اضغط هنا لرفع فيديوهات متعددة بلا حدود أو سحبها مباشرةً (MP4, WebM) 🎥'
                          : 'اضغط هنا لرفع صور متعددة بلا حدود أو سحبها مباشرةً 🖼️'
                        : activeMediaTab === 'video'
                        ? 'Click to select unlimited videos or drag & drop 🎥'
                        : 'Click to select unlimited photos or drag & drop 🖼️'}
                    </p>
                    <p className="text-[10px] text-slate-400 mt-0.5">
                      {language === 'ar'
                        ? 'يمكنك تحديد عدة ملفات دفعة واحدة من الاستوديو أو الكمبيوتر'
                        : 'Select multiple media files at once from gallery'}
                    </p>
                  </div>
                </div>
              </div>

              {/* Paste URL Bar */}
              <div className="flex gap-2 text-xs">
                <input
                  type="url"
                  placeholder={
                    activeMediaTab === 'video'
                      ? (language === 'ar' ? 'ألصق رابط فيديو مباشر (https://...)' : 'Paste direct video URL')
                      : (language === 'ar' ? 'أو ألصق رابط صورة مباشر (https://...)' : 'Or paste direct image URL')
                  }
                  value={pastedUrl}
                  onChange={(e) => setPastedUrl(e.target.value)}
                  className="flex-1 bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-slate-200 font-mono text-[11px] focus:outline-none focus:border-amber-500/50"
                />
                <button
                  type="button"
                  onClick={handleAddPastedUrl}
                  className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-amber-400 font-bold rounded-xl transition-all"
                >
                  {language === 'ar' ? 'إضافة' : 'Add'}
                </button>
              </div>

              {/* Videos Preview List */}
              {videosList.length > 0 && (
                <div className="space-y-2 pt-1">
                  <div className="flex items-center justify-between text-xs text-indigo-300 font-bold">
                    <span className="flex items-center gap-1">
                      <Film className="w-3.5 h-3.5 text-indigo-400" />
                      <span>{language === 'ar' ? `الفيديوهات المرفقة (${videosList.length} فيديو):` : `Uploaded Videos (${videosList.length}):`}</span>
                    </span>
                  </div>

                  <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
                    {videosList.map((vUrl, vIdx) => (
                      <div key={vIdx} className="relative rounded-xl overflow-hidden border border-indigo-500/40 bg-black max-h-44 p-1">
                        <div className="flex items-center justify-between text-[11px] px-2 py-1 text-slate-300">
                          <span>{language === 'ar' ? `فيديو #${vIdx + 1}` : `Video #${vIdx + 1}`}</span>
                          <button
                            type="button"
                            onClick={() => removeVideo(vIdx)}
                            className="text-red-400 hover:underline flex items-center gap-1 font-bold"
                          >
                            <Trash2 className="w-3 h-3" />
                            <span>{language === 'ar' ? 'حذف' : 'Remove'}</span>
                          </button>
                        </div>
                        <video src={vUrl} controls className="w-full max-h-36 object-contain mx-auto rounded-lg" />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Images Preview Gallery */}
              {imagesList.length > 0 && (
                <div className="space-y-2 pt-1">
                  <div className="flex items-center justify-between text-xs text-slate-300 font-bold">
                    <span className="flex items-center gap-1">
                      <ImageIcon className="w-3.5 h-3.5 text-amber-400" />
                      <span>{language === 'ar' ? `الصور المرفقة (${imagesList.length} صور):` : `Uploaded Photos (${imagesList.length}):`}</span>
                    </span>
                    <span className="text-[10px] text-slate-400 font-normal">
                      {language === 'ar' ? 'غير محدود ♾️' : 'Unlimited photo uploads'}
                    </span>
                  </div>

                  <div className="grid grid-cols-4 sm:grid-cols-5 gap-2 max-h-40 overflow-y-auto pr-1">
                    {imagesList.map((img, idx) => (
                      <div key={idx} className="relative group rounded-xl overflow-hidden border border-slate-800 bg-black aspect-square">
                        <img src={img} alt={`ad-img-${idx}`} className="w-full h-full object-cover" />
                        <button
                          type="button"
                          onClick={() => removeImage(idx)}
                          className="absolute top-1 right-1 p-1 bg-red-600/90 hover:bg-red-500 text-white rounded-lg opacity-90 transition-all shadow-md"
                          title="حذف هذه الصورة"
                        >
                          <Trash2 className="w-3 h-3" />
                        </button>
                        {idx === 0 && (
                          <span className="absolute bottom-1 left-1 bg-amber-500 text-slate-950 font-black text-[9px] px-1 rounded">
                            الرئيسية
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Featured Ad & Subscription Plans Section */}
            <div className="space-y-3 bg-gradient-to-r from-amber-950/40 via-slate-900 to-amber-950/40 border border-amber-500/40 p-4 rounded-2xl shadow-lg">
              <div className="flex items-center justify-between">
                <label className="font-bold text-amber-200 flex items-center gap-2 text-xs sm:text-sm">
                  <Crown className="w-4 h-4 text-amber-400" />
                  <span>{language === 'ar' ? 'باقات ترويج وتمييز الإعلان 👑🌟 (اختياري)' : 'Featured Ad Packages 👑🌟 (Optional)'}</span>
                </label>
                <span className="text-[10px] bg-amber-500/20 text-amber-300 border border-amber-500/30 px-2 py-0.5 rounded-full font-bold">
                  {language === 'ar' ? 'زيادة المشاهدات بـ 10 أضعاف' : '10x Views Boost'}
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                {/* Standard / Free Plan */}
                <div
                  onClick={() => setFeaturedPlan('standard')}
                  className={`p-3 rounded-xl border cursor-pointer transition-all flex flex-col justify-between ${
                    featuredPlan === 'standard'
                      ? 'bg-slate-900 border-slate-600 ring-2 ring-slate-400/50'
                      : 'bg-slate-950/60 border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-slate-300 text-xs">{language === 'ar' ? 'إعلان عادي' : 'Standard'}</span>
                      <span className="text-[10px] bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded font-bold">{language === 'ar' ? 'مجاني' : 'Free'}</span>
                    </div>
                    <p className="text-[10px] text-slate-400">{language === 'ar' ? 'ظهور عادي ضمن القائمة الحالية' : 'Standard placement in categories'}</p>
                  </div>
                </div>

                {/* Golden Featured Plan */}
                <div
                  onClick={() => setFeaturedPlan('golden')}
                  className={`p-3 rounded-xl border cursor-pointer transition-all flex flex-col justify-between relative overflow-hidden ${
                    featuredPlan === 'golden'
                      ? 'bg-amber-950/60 border-amber-400 ring-2 ring-amber-400/80 shadow-md shadow-amber-500/20'
                      : 'bg-slate-950/60 border-amber-500/30 hover:border-amber-400/60'
                  }`}
                >
                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-amber-300 text-xs flex items-center gap-1">
                        <Star className="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
                        <span>{language === 'ar' ? 'باقة ذهبية ⭐️' : 'Golden Plan'}</span>
                      </span>
                      <span className="text-[10px] bg-amber-500 text-slate-950 font-black px-1.5 py-0.5 rounded">
                        {language === 'ar' ? '$5 / شهر' : '$5/mo'}
                      </span>
                    </div>
                    <p className="text-[10px] text-amber-200/80">{language === 'ar' ? 'إطار ذهبي + تثبيت 3 أيام + 5X مشاهدات' : 'Golden frame + 3d top pin + 5X views'}</p>
                  </div>
                </div>

                {/* Diamond VIP Plan */}
                <div
                  onClick={() => setFeaturedPlan('vip')}
                  className={`p-3 rounded-xl border cursor-pointer transition-all flex flex-col justify-between relative overflow-hidden ${
                    featuredPlan === 'vip'
                      ? 'bg-gradient-to-br from-indigo-950 via-purple-950 to-slate-950 border-cyan-400 ring-2 ring-cyan-400 shadow-lg shadow-cyan-500/20'
                      : 'bg-slate-950/60 border-cyan-500/30 hover:border-cyan-400/60'
                  }`}
                >
                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-cyan-300 text-xs flex items-center gap-1">
                        <Crown className="w-3.5 h-3.5 text-yellow-400" />
                        <span>{language === 'ar' ? 'باقة VIP 👑💎' : 'Diamond VIP'}</span>
                      </span>
                      <span className="text-[10px] bg-gradient-to-r from-cyan-500 to-indigo-500 text-white font-black px-1.5 py-0.5 rounded">
                        {language === 'ar' ? '$12 / شهر' : '$12/mo'}
                      </span>
                    </div>
                    <p className="text-[10px] text-cyan-200/80">{language === 'ar' ? 'تصدّر الرئيسية + شارة تاج فخمة + 10X مشاهدات' : 'Top homepage pin + VIP Crown + 10X views'}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="pt-2 flex items-center gap-3">
              <button
                type="button"
                onClick={onClose}
                className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold rounded-xl transition-all"
              >
                {language === 'ar' ? 'إلغاء' : 'Cancel'}
              </button>
              <button
                type="submit"
                className="flex-1 py-3 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-slate-950 font-black rounded-xl shadow-lg shadow-amber-500/20 transition-all active:scale-95 flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4" />
                <span>{language === 'ar' ? 'نشر الإعلان الآن' : 'Publish Listing Now'}</span>
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};
